Skip to content
Navigation Menu
smartiqaorg
/
geometric_lib

Type / to search
Code
Issues
29
Pull requests
761
Actions
Projects
Security
Insights
Zazering patch 1 #1222
 Closed
zazering wants to merge 3 commits into smartiqaorg:main from zazering:zazering-patch-1-1 
+48 −0 
 Conversation 0
 Commits 3
 Checks 0
 Files changed 1
File filter 
 
Create python-app.yml
@zazering
zazering authored 6 minutes ago 
commit e3f188784e57999d52748ec62b0be5bbdce011e0
 48 changes: 48 additions & 0 deletions48  
.github/workflows/python-app.yml
Original file line number	Original file line	Diff line number	Diff line change
@@ -0,0 +1,48 @@
name: Unit Tests

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Output Information
        run: |
          echo "Your Full Name: [Your Full Name]"
          echo "Group Number: [Your Group Number]"
          echo "GitHub Nickname: ${{ github.actor }}"
          
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Check dir
        run: pwd

      - name: Check content
        run: ls -la .

      - name: Check geometric_lib
        run: ls -la geometric_lib

      - name: Install Dependencies
        run: |
          pip -m install --upgrade pip
          pip install -r requirements.txt
          working-direcotry: geometric_lib
        
      - name: Run Tests
        run: pytest

      - name: Check Code Style
        run: flake8 .
Footer
© 2024 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact
Manage cookies
Do not share my personal information
Zazering patch 1 by zazering · Pull Request #1222 · smartiqaorg/geometric_lib
