name: Unit Tests

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - master
      - release
      - develop
      - feat/tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Code check
        uses: actions/checkout@v2
      
      - name: Output info
        run: |
          echo "Your name: [Nikulin Mark Kirillovich]"
          echo "Group number: [M3110]"
          echo "GitHub nickname: ${{ github.actor }}"
          
      - name: Download python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          
      - name: Update
        run: python -m pip install --upgrade pip
        
      - name: Check content
        run: ls -la
        
      - name: install dependencies
        run: pip install -r requirements.txt
        
      - name: Run tests
        run: pytest
        
      - name: Check code style
        run: flake8 .# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
